autocomplete_index_length: 4
default_contact_email: "contact@kipscore.com"
default_noreply_email: "noreply@kipscore.com"
twitter_page_url: "https://twitter.com/kipscore"
facebook_page_url: "http://www.facebook.com/pages/Kipscore/150146748477630"
rankings: ["Pfs Damski Open", "Pfs Open"]
